version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     dockerfile: ./nginx.dockerfile
  #     context: . 
  #   image: adilsonf/nginx
  #   ports:
  #     - "80:80"
  #   networks:
  #     - production-network
  #   depends_on:
  #     - "node1"
  #     - "node2"
  #     - "node3"
  mongodb:
    image: mongo
    networks: 
      - production-network
  node1:
    container_name: alura-books-1
    build:
      dockerfile: ./alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on:
      - "mongodb"
  node2:
    container_name: alura-books-2
    build:
      dockerfile: ./alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on:
      - "mongodb"
  node3:
    container_name: alura-books-3
    build:
      dockerfile: ./alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on:
      - "mongodb"
networks:
  production-network:
    driver: bridge
